# Generated by Django 4.1.7 on 2023-03-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiondetail',
            options={'ordering': ['id']},
        ),
    ]
