# Generated by Django 4.1.7 on 2023-03-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_transactiondetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order'),
        ),
    ]
