# Generated by Django 4.1.7 on 2023-03-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_transactiondetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Success', max_length=7),
        ),
    ]
