# Generated by Django 4.1.7 on 2023-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderinvoice_delete_transactiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinvoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
